import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import Sidebar from "../../components/Sidebar";

import * as React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ClerkProvider>
          <Sidebar children={children} />
        </ClerkProvider>
      </body>
    </html>
  );
}
