import { ClerkProvider } from "@clerk/nextjs";
import Tobar from "../../components/Topbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      {/* <head>
        <script async src='https://www.youtube.com/iframe_api'></script>
      </head> */}
      <ClerkProvider>
        <body className='bg-slate-300'>
          <Tobar />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
