import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <ClerkProvider>
        <body className='bg-slate-300'>{children}</body>
      </ClerkProvider>
    </html>
  );
}
